### ISSUE TITLE
[BUG] Starting the video meeting from the Webphone for the first time ask for login.

### ISSUE THREAD

**Issue by rverma-1611** [iotum/community#24]
Starting the video meeting from the Webphone for the first time ask for login.

**To Reproduce**
1. Open a new incognito window login to portal
2. Open the webphone
3. Click on the video sidebar
4. Click on the start video meeting from the sidebar
5. It opens the new video meeting tab that asks for login.

Please refer to the attached screen recording

https://github.com/user-attachments/assets/a5cd37a0-39e6-4f1d-aed9-255fdf0d3b65

**Comment by noamtiotum** [comment]
This has been resolved.

**Comment by rverma-1611** [comment]
@noamtiotum 
I still see this issue with both the staging and the production setup.

Here is the screen recording with the staging server:

https://github.com/user-attachments/assets/700ec980-cc94-4ccb-b2d1-a01b64aacdc1


Here is the screen recording with the production server:

https://github.com/user-attachments/assets/1fddea5c-e68b-4578-8dcf-2fe2e586246f

**Comment by jerry2013** [comment]
can you try deleting all cookies from all subdomains of `<xyz>.meet-staging.netsapiens.com`?

**Comment by rverma-1611** [comment]
I did this in an Incognito window; there should be no old cookies.

**Comment by jerry2013** [comment]
ah sorry i missed the "incognito" part. that mode has a few extra security/privacy settings turned on which blocks 3rd party cookie from passing through and causes the loss of session when opening a pop-up cross different TLDs.

we will discuss whether using incognito mode is what we'll natively support next week.

in the mean time, to support such scenario you can [intercept the meeting action](https://github.com/iotum/callbridge-js/blob/main/wiki/enums/MeetingAction.md) and use managed pop up widget (similar to how the webphone opens "premium video" popup)

**Comment by rverma-1611** [comment]
Thanks, Jerry!  It's working fine in a normal window.
